repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--check, --config=pyproject.toml]

      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [python]
        args: [--config=pyproject.toml, --output-format=concise]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [--config-file=pyproject.toml]
