version: '3.9'

services:
  app:
    build:
      context: .
      target: ${TARGET:-development}
    environment:
      ENV: dev
      PG_SERVER: postgres
    ports:
      - '8081:8080'
    depends_on:
      - migration
      - postgres

  migration:
    build:
      context: .
      target: migration
    environment:
      ENV: dev
      PG_SERVER: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
